"""add_server_default_to_user_state.

Revision ID: fe703c90e64f
Revises: f38b3bd4bdfc
Create Date: 2026-01-16 16:11:38.686058

"""

# revision identifiers, used by Alembic.
revision = "fe703c90e64f"
down_revision = "f38b3bd4bdfc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
