"""add_server_default_to_user_id.

Revision ID: 9dd390695b68
Revises: b0ea44009f6d
Create Date: 2026-01-16 15:53:37.873348

"""

# revision identifiers, used by Alembic.
revision = "9dd390695b68"
down_revision = "b0ea44009f6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
