"""rename_device_updated_at_to_modified_at.

Revision ID: eb2aef34c293
Revises: a7224092b2f2
Create Date: 2026-01-16 13:11:22.688741

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eb2aef34c293"
down_revision = "a7224092b2f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        schema="user_app",
    )
    op.drop_column("device", "updated_at", schema="user_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        schema="user_app",
    )
    op.drop_column("device", "modified_at", schema="user_app")
    # ### end Alembic commands ###
