"""add_login_type_check_constraint.

Revision ID: b0ea44009f6d
Revises: f80676d26dd7
Create Date: 2026-01-16 15:49:00.201554

"""

# revision identifiers, used by Alembic.
revision = "b0ea44009f6d"
down_revision = "f80676d26dd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
