"""change_login_type_to_varchar.

Revision ID: f80676d26dd7
Revises: eb2aef34c293
Create Date: 2026-01-16 15:47:00.632353

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f80676d26dd7"
down_revision = "eb2aef34c293"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "login_type",
        existing_type=postgresql.ENUM("google", "facebook", "apple", name="logintype"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        schema="user_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "login_type",
        existing_type=sa.VARCHAR(length=50),
        type_=postgresql.ENUM("google", "facebook", "apple", name="logintype"),
        existing_nullable=True,
        schema="user_app",
    )
    # ### end Alembic commands ###
