"""initial_schema_final.

Revision ID: a7224092b2f2
Revises: 
Create Date: 2026-01-16 12:40:16.042115

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a7224092b2f2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_coupon",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "app_consumer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("client_id", sa.VARCHAR(length=40), nullable=True),
        sa.Column("client_secret", sa.VARCHAR(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("legacy_consumer_key", sa.VARCHAR(length=128), nullable=True),
        sa.Column("legacy_consumer_secret", sa.VARCHAR(length=128), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=True),
        sa.Column("partner_code", sa.VARCHAR(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_table(
        "invite_coupon",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "used", "expired", name="couponstatus"),
            nullable=False,
        ),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="user_app",
    )
    op.create_table(
        "otp_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("otp", sa.VARCHAR(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_table(
        "otp_verification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("mobile", sa.VARCHAR(length=20), nullable=True),
        sa.Column("calling_code", sa.VARCHAR(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_otp_verification_created_at"),
        "otp_verification",
        ["created_at"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_otp_verification_email"),
        "otp_verification",
        ["email"],
        unique=False,
        schema="user_app",
    )
    op.create_table(
        "platform",
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("platform_name", sa.VARCHAR(), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("platform_id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_platform_platform_name"),
        "platform",
        ["platform_name"],
        unique=True,
        schema="user_app",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("mobile", sa.VARCHAR(length=20), nullable=False),
        sa.Column("calling_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("is_password_set", sa.Boolean(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("inactive", "active", "blocked", "deactivated", name="userstate"),
            nullable=False,
        ),
        sa.Column("is_email_verified", sa.Boolean(), nullable=True),
        sa.Column("is_mobile_verified", sa.Boolean(), nullable=True),
        sa.Column("account_locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=True),
        sa.Column(
            "login_type",
            sa.Enum("google", "facebook", "apple", name="logintype"),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum("regular", "creator", name="usertype"),
            nullable=False,
        ),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivation_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_user_created_at"),
        "user",
        ["created_at"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_user_email"),
        "user",
        ["email"],
        unique=True,
        schema="user_app",
    )
    op.create_table(
        "invite_device",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("coupon_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["invite_coupon.id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "device",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.VARCHAR(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("device_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("device_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("platform", sa.VARCHAR(length=20), nullable=True),
        sa.Column("device_ip", postgresql.INET(), nullable=True),
        sa.Column("is_vpn", sa.Boolean(), nullable=True),
        sa.Column("is_anonymous_proxy", sa.Boolean(), nullable=True),
        sa.Column("residency_verified", sa.Boolean(), nullable=True),
        sa.Column("is_rooted", sa.Boolean(), nullable=True),
        sa.Column("is_jailbroken", sa.Boolean(), nullable=True),
        sa.Column("device_active", sa.Boolean(), nullable=True),
        sa.Column("drm_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("hardware_encryption", sa.Boolean(), nullable=True),
        sa.Column("transaction_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("is_ip_legal", sa.Boolean(), nullable=True),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("user_token", sa.Text(), nullable=True),
        sa.Column("native_token", sa.Text(), nullable=True),
        sa.Column("date_deactivated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("country_code", sa.VARCHAR(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["platform"],
            ["user_app.platform.platform_name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_date_deactivated"),
        "device",
        ["date_deactivated"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_device_ip"),
        "device",
        ["device_ip"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_device_type"),
        "device",
        ["device_type"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_is_jailbroken"),
        "device",
        ["is_jailbroken"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_is_rooted"),
        "device",
        ["is_rooted"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_is_vpn"),
        "device",
        ["is_vpn"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_platform"),
        "device",
        ["platform"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_serial_number"),
        "device",
        ["serial_number"],
        unique=True,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_device_user_id"),
        "device",
        ["user_id"],
        unique=False,
        schema="user_app",
    )
    op.create_table(
        "social_identity_provider",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), nullable=False),
        sa.Column("provider_user_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_social_identity_provider_user_id"),
        "social_identity_provider",
        ["user_id"],
        unique=False,
        schema="user_app",
    )
    op.create_table(
        "user_auth_token",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("token", sa.Text(), nullable=True),
        sa.Column("app_consumer_id", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.VARCHAR(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("oauth1_token", sa.VARCHAR(length=128), nullable=True),
        sa.Column("oauth1_token_secret", sa.VARCHAR(length=128), nullable=True),
        sa.Column("partner_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_consumer_id"],
            ["user_app.app_consumer.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        schema="user_app",
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("firstname", sa.VARCHAR(length=100), nullable=True),
        sa.Column("lastname", sa.VARCHAR(length=100), nullable=True),
        sa.Column("country_code", sa.VARCHAR(length=10), nullable=True),
        sa.Column("gender", sa.CHAR(length=10), nullable=True),
        sa.Column("about_me", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("avatar_id", sa.Integer(), nullable=True),
        sa.Column("nick_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_table(
        "authentication_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("auth_token", sa.Text(), nullable=False),
        sa.Column("token_secret", sa.Text(), nullable=True),
        sa.Column("auth_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("platform", sa.VARCHAR(length=20), nullable=True),
        sa.Column("app_version", sa.VARCHAR(length=20), nullable=True),
        sa.Column("country_code", sa.VARCHAR(length=10), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("logged_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("logout_reason", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["user_app.device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_authentication_session_auth_token"),
        "authentication_session",
        ["auth_token"],
        unique=True,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_authentication_session_auth_token_expiry"),
        "authentication_session",
        ["auth_token_expiry"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_authentication_session_device_id"),
        "authentication_session",
        ["device_id"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_authentication_session_user_id"),
        "authentication_session",
        ["user_id"],
        unique=False,
        schema="user_app",
    )
    op.create_table(
        "invite_device",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("coupon_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["user_app.invite_coupon.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["user_app.device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="user_app",
    )
    op.create_table(
        "waitlist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("mobile", sa.VARCHAR(length=20), nullable=False),
        sa.Column("calling_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("queue_number", sa.Integer(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["user_app.device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_app.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_waitlist_device_id"),
        "waitlist",
        ["device_id"],
        unique=True,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_waitlist_email"),
        "waitlist",
        ["email"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_waitlist_is_verified"),
        "waitlist",
        ["is_verified"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_waitlist_queue_number"),
        "waitlist",
        ["queue_number"],
        unique=False,
        schema="user_app",
    )
    op.create_table(
        "friend_invite",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inviter_id", sa.UUID(), nullable=False),
        sa.Column("invited_email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("invited_mobile", sa.VARCHAR(length=20), nullable=False),
        sa.Column("invited_calling_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.Column("invite_token", sa.VARCHAR(length=255), nullable=True),
        sa.Column("invite_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_user_id", sa.UUID(), nullable=True),
        sa.Column("waitlist_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["user_app.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["user_app.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["waitlist_id"],
            ["user_app.waitlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_friend_invite_invite_token"),
        "friend_invite",
        ["invite_token"],
        unique=True,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_friend_invite_invited_email"),
        "friend_invite",
        ["invited_email"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_friend_invite_invited_user_id"),
        "friend_invite",
        ["invited_user_id"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_friend_invite_inviter_id"),
        "friend_invite",
        ["inviter_id"],
        unique=False,
        schema="user_app",
    )
    op.create_index(
        op.f("ix_user_app_friend_invite_status"),
        "friend_invite",
        ["status"],
        unique=False,
        schema="user_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_app_friend_invite_status"),
        table_name="friend_invite",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_friend_invite_inviter_id"),
        table_name="friend_invite",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_friend_invite_invited_user_id"),
        table_name="friend_invite",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_friend_invite_invited_email"),
        table_name="friend_invite",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_friend_invite_invite_token"),
        table_name="friend_invite",
        schema="user_app",
    )
    op.drop_table("friend_invite", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_waitlist_queue_number"),
        table_name="waitlist",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_waitlist_is_verified"),
        table_name="waitlist",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_waitlist_email"),
        table_name="waitlist",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_waitlist_device_id"),
        table_name="waitlist",
        schema="user_app",
    )
    op.drop_table("waitlist", schema="user_app")
    op.drop_table("invite_device", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_authentication_session_user_id"),
        table_name="authentication_session",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_authentication_session_device_id"),
        table_name="authentication_session",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_authentication_session_auth_token_expiry"),
        table_name="authentication_session",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_authentication_session_auth_token"),
        table_name="authentication_session",
        schema="user_app",
    )
    op.drop_table("authentication_session", schema="user_app")
    op.drop_table("user_profile", schema="user_app")
    op.drop_table("user_auth_token", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_social_identity_provider_user_id"),
        table_name="social_identity_provider",
        schema="user_app",
    )
    op.drop_table("social_identity_provider", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_device_user_id"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_serial_number"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_platform"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_is_vpn"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_is_rooted"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_is_jailbroken"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_device_type"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_device_ip"),
        table_name="device",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_device_date_deactivated"),
        table_name="device",
        schema="user_app",
    )
    op.drop_table("device", schema="user_app")
    op.drop_table("invite_device")
    op.drop_index(op.f("ix_user_app_user_email"), table_name="user", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_user_created_at"),
        table_name="user",
        schema="user_app",
    )
    op.drop_table("user", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_platform_platform_name"),
        table_name="platform",
        schema="user_app",
    )
    op.drop_table("platform", schema="user_app")
    op.drop_index(
        op.f("ix_user_app_otp_verification_email"),
        table_name="otp_verification",
        schema="user_app",
    )
    op.drop_index(
        op.f("ix_user_app_otp_verification_created_at"),
        table_name="otp_verification",
        schema="user_app",
    )
    op.drop_table("otp_verification", schema="user_app")
    op.drop_table("otp_token", schema="user_app")
    op.drop_table("invite_coupon", schema="user_app")
    op.drop_table("app_consumer", schema="user_app")
    op.drop_table("invite_coupon")
    # ### end Alembic commands ###
