"""make_mobile_nullable.

Revision ID: f38b3bd4bdfc
Revises: 9dd390695b68
Create Date: 2026-01-16 16:05:29.555734

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f38b3bd4bdfc"
down_revision = "9dd390695b68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "mobile",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        schema="user_app",
    )
    op.alter_column(
        "user",
        "calling_code",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        schema="user_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "calling_code",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        schema="user_app",
    )
    op.alter_column(
        "user",
        "mobile",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        schema="user_app",
    )
    # ### end Alembic commands ###
