"""change_auth_session_device_id_to_varchar.

Revision ID: fb442d28459b
Revises: c9cb1c57f873
Create Date: 2026-01-16 16:49:08.931990

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fb442d28459b"
down_revision = "c9cb1c57f873"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing FK first
    op.drop_constraint(
        "authentication_session_device_id_fkey",
        "authentication_session",
        schema="user_app",
        type_="foreignkey",
    )

    op.alter_column(
        "authentication_session",
        "device_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="user_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "authentication_session",
        "device_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        schema="user_app",
    )
    # ### end Alembic commands ###
