"""add_server_default_to_auth_session_id.

Revision ID: c9cb1c57f873
Revises: fe703c90e64f
Create Date: 2026-01-16 16:41:08.534152

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c9cb1c57f873"
down_revision = "fe703c90e64f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "authentication_session",
        "id",
        server_default=sa.text("gen_random_uuid()"),
        existing_type=sa.UUID(),
        existing_nullable=False,
        schema="user_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "authentication_session",
        "id",
        server_default=None,
        existing_type=sa.UUID(),
        existing_nullable=False,
        schema="user_app",
    )
    # ### end Alembic commands ###
